### ISSUE TITLE
Just started reading the book and I cannot run the examples.

### ISSUE THREAD

**Issue by danleedotorg** [PacktPublishing/Layered-Design-for-Ruby-on-Rails-Applications#2]
Running this command:

```bash
 ruby Chapter01/01-request-gc-stats.rb
```

will trigger this error:

```bash
DEPRECATION WARNING: Support for `config.active_support.cache_format_version = 6.1` has been deprecated and will be removed in Rails 7.2.

Check the Rails upgrade guide at https://guides.rubyonrails.org/upgrading_ruby_on_rails.html#new-activesupport-cache-serialization-format
for more information on how to upgrade.
 (called from <top (required)> at /home/danleedotorg/Repos/Layered-Design-for-Ruby-on-Rails-Applications/lib/boot.rb:4)
/home/danleedotorg/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/activerecord-7.1.2/lib/active_record.rb:246:in `legacy_connection_handling=': The `legacy_connection_handling` setter was deprecated in 7.0 and removed in 7.1, but is still defined in your configuration. Please remove this call as it no longer has any effect." (ArgumentError)

    raise ArgumentError, <<~MSG.squish
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        from /home/danleedotorg/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/activerecord-7.1.2/lib/active_record/railtie.rb:290:in `block (3 levels) in <class:Railtie>'
        from /home/danleedotorg/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/activerecord-7.1.2/lib/active_record/railtie.rb:282:in `each'
        from /home/danleedotorg/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/activerecord-7.1.2/lib/active_record/railtie.rb:282:in `block (2 levels) in <class:Railtie>'
        from /home/danleedotorg/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/activesupport-7.1.2/lib/active_support/lazy_load_hooks.rb:97:in `class_eval'
        from /home/danleedotorg/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/activesupport-7.1.2/lib/active_support/lazy_load_hooks.rb:97:in `block in execute_hook'
        from /home/danleedotorg/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/activesupport-7.1.2/lib/active_support/lazy_load_hooks.rb:87:in `with_execution_control'
        from /home/danleedotorg/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/activesupport-7.1.2/lib/active_support/lazy_load_hooks.rb:92:in `execute_hook'
        from /home/danleedotorg/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/activesupport-7.1.2/lib/active_support/lazy_load_hooks.rb:62:in `block in on_load'
        from /home/danleedotorg/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/activesupport-7.1.2/lib/active_support/lazy_load_hooks.rb:61:in `each'
        from /home/danleedotorg/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/activesupport-7.1.2/lib/active_support/lazy_load_hooks.rb:61:in `on_load'
        from /home/danleedotorg/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/activerecord-7.1.2/lib/active_record/railtie.rb:263:in `block in <class:Railtie>'
        from /home/danleedotorg/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/railties-7.1.2/lib/rails/initializable.rb:32:in `instance_exec'
        from /home/danleedotorg/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/railties-7.1.2/lib/rails/initializable.rb:32:in `run'
        from /home/danleedotorg/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/railties-7.1.2/lib/rails/initializable.rb:61:in `block in run_initializers'
        from /home/danleedotorg/.rbenv/versions/3.2.2/lib/ruby/3.2.0/tsort.rb:228:in `block in tsort_each'
        from /home/danleedotorg/.rbenv/versions/3.2.2/lib/ruby/3.2.0/tsort.rb:350:in `block (2 levels) in each_strongly_connected_component'
        from /home/danleedotorg/.rbenv/versions/3.2.2/lib/ruby/3.2.0/tsort.rb:431:in `each_strongly_connected_component_from'
        from /home/danleedotorg/.rbenv/versions/3.2.2/lib/ruby/3.2.0/tsort.rb:349:in `block in each_strongly_connected_component'
        from /home/danleedotorg/.rbenv/versions/3.2.2/lib/ruby/3.2.0/tsort.rb:347:in `each'
        from /home/danleedotorg/.rbenv/versions/3.2.2/lib/ruby/3.2.0/tsort.rb:347:in `call'
        from /home/danleedotorg/.rbenv/versions/3.2.2/lib/ruby/3.2.0/tsort.rb:347:in `each_strongly_connected_component'
        from /home/danleedotorg/.rbenv/versions/3.2.2/lib/ruby/3.2.0/tsort.rb:226:in `tsort_each'
        from /home/danleedotorg/.rbenv/versions/3.2.2/lib/ruby/3.2.0/tsort.rb:205:in `tsort_each'
        from /home/danleedotorg/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/railties-7.1.2/lib/rails/initializable.rb:60:in `run_initializers'
        from /home/danleedotorg/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/railties-7.1.2/lib/rails/application.rb:423:in `initialize!'
        from /home/danleedotorg/Repos/Layered-Design-for-Ruby-on-Rails-Applications/lib/boot.rb:4:in `<top (required)>'
        from /home/danleedotorg/Repos/Layered-Design-for-Ruby-on-Rails-Applications/Chapter01/prelude.rb:12:in `require_relative'
        from /home/danleedotorg/Repos/Layered-Design-for-Ruby-on-Rails-Applications/Chapter01/prelude.rb:12:in `<top (required)>'
        from Chapter01/01-request-gc-stats.rb:1:in `require_relative'
        from Chapter01/01-request-gc-stats.rb:1:in `<main>'

```

It looks like the issue is that I have a newer version of ActiveSupport installed. I ended up fixing this issue by uninstalling all my gems for my ruby version.

Do you have any suggestions on how to make this run without the need of uninstalling gems? (Sorry if this is a noob question, I do not spend a lot of my time writing ruby code outside of a Rails context.)

**Comment by palkan** [comment]
Thanks for the report!

Looks like the final Rails 7.1 release broke some configuration settings. Pushed an upgrade that fixes this.

**Comment by CloudCodeCraft** [comment]
Thanks, it works now! Appreciate the quick fix!
